# Generated by Django 3.0 on 2026-02-27 17:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('gender', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('photo', models.CharField(max_length=250)),
                ('qualification', models.CharField(max_length=250)),
                ('place', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('pin', models.CharField(max_length=20)),
                ('join_date', models.DateField(default='2026-01-14')),
                ('experience', models.CharField(max_length=20)),
                ('department', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('salary', models.FloatField()),
                ('status', models.CharField(default='Active', max_length=20)),
                ('USER', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('document', models.CharField(max_length=400)),
                ('title', models.CharField(default='', max_length=500)),
                ('hashvalue', models.CharField(default='', max_length=1000)),
                ('STAFF', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Staff')),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('complaint', models.CharField(max_length=1000)),
                ('reply', models.CharField(max_length=1000)),
                ('status', models.CharField(max_length=100)),
                ('STAFF', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Staff')),
            ],
        ),
    ]
